-- Gudeg Mbah Tjip - Supabase database
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.foods (
  id text primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  image_path text,
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_code text not null unique,
  order_type text not null check (order_type in ('dinein', 'takeaway', 'preorder')),
  customer_name text,
  customer_phone text,
  table_number integer,
  pickup_date date,
  pickup_time time,
  notes text,
  payment_method text not null check (payment_method in ('qris', 'va', 'bank', 'cash')),
  total integer not null check (total >= 0),
  status text not null default 'Diproses',
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  quantity integer not null check (quantity > 0),
  unit_price integer not null check (unit_price >= 0),
  subtotal integer not null check (subtotal >= 0),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on public.orders(created_at desc);
create index if not exists order_items_order_id_idx on public.order_items(order_id);

-- Seed menu data used by the current web app.
insert into public.foods (id, name, category, price, image_path)
values
  ('food-1', 'Nasi Putih', 'Food', 5000, 'assets/nasi-putih.jpg'),
  ('food-2', 'Tempe Bacem', 'Food', 4000, 'assets/tempe-bacem.jpg'),
  ('food-3', 'Tahu Bacem', 'Food', 4000, 'assets/tahu-bacem.jpg'),
  ('food-4', 'Gudeg', 'Food', 8000, 'assets/gudeg.jpg'),
  ('drink-1', 'Teh Tawar', 'Drink', 2000, 'assets/teh-tawar.jpg'),
  ('drink-2', 'Teh Manis', 'Drink', 3000, 'assets/teh-manis.jpg'),
  ('drink-3', 'Es Teh Lemon', 'Drink', 4000, 'assets/es-teh-lemon.jpg'),
  ('drink-4', 'Kopi', 'Drink', 5000, 'assets/kopi.jpg')
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  price = excluded.price,
  image_path = excluded.image_path;

-- Anonymous user testing: allow the public web app to create orders.
-- We intentionally do NOT allow public update/delete/select of customer orders.
alter table public.foods enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Public can read available foods" on public.foods;
create policy "Public can read available foods"
  on public.foods for select
  to anon, authenticated
  using (is_available = true);

drop policy if exists "Public can create orders" on public.orders;
create policy "Public can create orders"
  on public.orders for insert
  to anon, authenticated
  with check (true);

drop policy if exists "Public can create order items" on public.order_items;
create policy "Public can create order items"
  on public.order_items for insert
  to anon, authenticated
  with check (true);


-- IMPORTANT for new Supabase projects: tables are not automatically exposed
-- to the Data API. These grants make only the operations needed by this
-- anonymous ordering app available through the publishable key.
grant select on table public.foods to anon, authenticated;
grant insert on table public.orders to anon, authenticated;
grant insert on table public.order_items to anon, authenticated;

-- order_items.id is generated by an identity sequence when the row is inserted.
grant usage, select on sequence public.order_items_id_seq to anon, authenticated;
